"""PDF export for investigation reports."""
from __future__ import annotations

import uuid
from pathlib import Path

import structlog
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ...core.database import get_db
from ...models.report import Report

logger = structlog.get_logger(__name__)
router = APIRouter(prefix="/export", tags=["export"])

TEMPLATE_DIR = Path(__file__).parent.parent.parent / "templates"

PDF_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page {
    size: A4;
    margin: 20mm 18mm 24mm 18mm;
    @bottom-center {
      content: "Generated by ProcureWatch | procurewatch.in | Confidential — Page " counter(page) " of " counter(pages);
      font-family: monospace;
      font-size: 8pt;
      color: #666;
    }
  }
  body {
    font-family: "DejaVu Sans", Arial, sans-serif;
    font-size: 10pt;
    color: #111;
    background: #fff;
    margin: 0;
    line-height: 1.55;
  }
  .header {
    border-bottom: 2.5pt solid #c0392b;
    padding-bottom: 10pt;
    margin-bottom: 18pt;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
  }
  .logo {
    font-family: monospace;
    font-size: 16pt;
    font-weight: bold;
    letter-spacing: 0.05em;
    color: #c0392b;
  }
  .meta {
    font-family: monospace;
    font-size: 8pt;
    color: #555;
    text-align: right;
  }
  h1 { font-size: 14pt; font-weight: 700; color: #111; margin: 0 0 6pt; line-height: 1.3; }
  h2 { font-size: 11pt; font-weight: 700; color: #c0392b; margin: 18pt 0 6pt;
       text-transform: uppercase; letter-spacing: 0.06em; border-bottom: 0.5pt solid #ddd;
       padding-bottom: 3pt; }
  .risk-badge {
    display: inline-block;
    padding: 2pt 8pt;
    border-radius: 2pt;
    font-family: monospace;
    font-size: 9pt;
    font-weight: bold;
    letter-spacing: 0.08em;
  }
  .risk-CRITICAL { background: #fde8e8; color: #c0392b; border: 0.5pt solid #c0392b; }
  .risk-HIGH     { background: #fef3e2; color: #d35400; border: 0.5pt solid #e67e22; }
  .risk-MEDIUM   { background: #eafaf1; color: #1e8449; border: 0.5pt solid #27ae60; }
  p { margin: 0 0 8pt; }
  table { width: 100%; border-collapse: collapse; margin: 8pt 0; }
  th { background: #f5f5f5; text-align: left; padding: 5pt 7pt;
       font-size: 8pt; font-weight: 700; text-transform: uppercase;
       letter-spacing: 0.05em; color: #555; border-bottom: 1pt solid #ddd; }
  td { padding: 5pt 7pt; border-bottom: 0.5pt solid #eee; font-size: 9.5pt; vertical-align: top; }
  .sev-critical { color: #c0392b; font-weight: bold; font-size: 8pt; }
  .sev-high     { color: #d35400; font-weight: bold; font-size: 8pt; }
  .sev-medium   { color: #1e8449; font-weight: bold; font-size: 8pt; }
  ol, ul { margin: 4pt 0 8pt; padding-left: 18pt; }
  li { margin-bottom: 4pt; }
  .data-callout {
    font-family: monospace;
    background: #f9f9f9;
    border-left: 3pt solid #c0392b;
    padding: 6pt 10pt;
    margin: 8pt 0;
    font-size: 9pt;
    color: #333;
  }
  .rti-item {
    border: 0.5pt solid #ddd;
    border-radius: 2pt;
    padding: 7pt 10pt;
    margin: 5pt 0;
    background: #fdfdfd;
  }
  .rti-num {
    font-family: monospace;
    font-weight: bold;
    color: #c0392b;
    margin-right: 6pt;
  }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="logo">PROCUREWATCH</div>
    <div style="font-size:8pt;color:#888;margin-top:2pt;">Government Procurement Intelligence</div>
  </div>
  <div class="meta">
    Generated: {{ generated_date }}<br>
    Report ID: {{ report_id }}<br>
    Classification: CONFIDENTIAL
  </div>
</div>

<h1>{{ title }}</h1>
<div style="margin: 6pt 0 14pt;">
  <span class="risk-badge risk-{{ risk_level }}">{{ risk_level }} RISK</span>
  <span style="font-family:monospace;font-size:8pt;color:#888;margin-left:10pt;">
    {{ tender_count }} tender(s) analyzed
  </span>
</div>

<h2>Executive Summary</h2>
<p>{{ executive_summary }}</p>

<h2>Red Flags Identified</h2>
<table>
  <tr>
    <th>Flag</th>
    <th>Severity</th>
    <th>Description</th>
  </tr>
  {% for flag in red_flags %}
  <tr>
    <td style="font-weight:600;">{{ flag.flag }}</td>
    <td><span class="sev-{{ flag.severity }}">{{ flag.severity | upper }}</span></td>
    <td>{{ flag.description }}</td>
  </tr>
  {% endfor %}
</table>

<h2>Evidence Analysis</h2>
{% for para in evidence_paragraphs %}
<p>{{ para }}</p>
{% endfor %}

<h2>Comparative Analysis</h2>
<div class="data-callout">{{ comparative_analysis }}</div>

<h2>RTI Questions</h2>
{% for i, q in rti_questions %}
<div class="rti-item">
  <span class="rti-num">{{ i }}.</span>{{ q }}
</div>
{% endfor %}

<h2>Recommended Actions</h2>
<ol>
{% for action in recommended_actions %}
  <li>{{ action }}</li>
{% endfor %}
</ol>

{% if estimated_loss %}
<div class="data-callout" style="margin-top:16pt;">
  <strong>Estimated Public Money at Risk:</strong> {{ estimated_loss }}
</div>
{% endif %}

</body>
</html>"""


@router.get("/reports/{report_id}/pdf")
async def export_report_pdf(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
) -> Response:
    result = await db.execute(
        select(Report).where(Report.id == report_id, Report.deleted_at.is_(None))
    )
    report = result.scalar_one_or_none()
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")
    if report.status != "ready":
        raise HTTPException(status_code=409, detail=f"Report is {report.status}, not ready for export")

    try:
        from jinja2 import Environment
        from datetime import datetime, timezone

        sections = report.sections or {}
        red_flags = sections.get("red_flags", [])
        evidence_text: str = sections.get("evidence_analysis", "")
        evidence_paragraphs = [p.strip() for p in evidence_text.split("\n\n") if p.strip()] or [evidence_text]
        rti_raw = sections.get("rti_questions", [])
        rti_questions = list(enumerate(rti_raw, 1))

        env = Environment(autoescape=True)
        template = env.from_string(PDF_TEMPLATE)
        html = template.render(
            title=report.title or "Investigation Brief",
            risk_level=report.risk_level or "HIGH",
            report_id=str(report_id)[:8].upper(),
            generated_date=datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC"),
            tender_count=len(report.tender_ids or []),
            executive_summary=sections.get("executive_summary", ""),
            red_flags=red_flags,
            evidence_paragraphs=evidence_paragraphs,
            comparative_analysis=sections.get("comparative_analysis", ""),
            rti_questions=rti_questions,
            recommended_actions=sections.get("recommended_actions", []),
            estimated_loss=sections.get("estimated_loss", ""),
        )

        from weasyprint import HTML
        pdf_bytes = HTML(string=html, base_url=None).write_pdf()

        safe_title = (report.title or "report")[:40].replace(" ", "_").replace("/", "-")
        filename = f"procurewatch_{safe_title}_{str(report_id)[:8]}.pdf"

        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    except ImportError:
        raise HTTPException(status_code=503, detail="WeasyPrint not available — rebuild API container")
    except Exception as exc:
        logger.exception("pdf_generation_failed", report_id=str(report_id))
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}")
